FROM python:3.12-slim
WORKDIR /app

COPY requirements.txt .
COPY wheels-linux/ /wheels/
RUN pip install --no-cache-dir --find-links=/wheels -r requirements.txt

COPY . .
RUN mkdir -p /app/.streamlit && cp streamlit_app.toml /app/.streamlit/config.toml

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
